menu:
- {name: 'Research', url: '/research'}
- {name: 'Resume', url: '/resume'}
- {name: 'Teaching', url: '/teaching'}

social:
- {icon: 'bluesky', link: 'https://bsky.app/profile/lpaluskiewicz.bsky.social'}
- {icon: 'linkedin', link: 'https://fr.linkedin.com/in/luc-paluskiewicz-1226a6164'}
